---
# Common variables for all hosts
ansible_python_interpreter: /usr/bin/python3
project_name: myapp
app_user: appuser
app_dir: "/home/{{ app_user }}/{{ project_name }}"

# Docker-related variables
docker_registry: "ahmedmostafa22" 
image_name: "{{ docker_registry }}/{{ project_name }}"

# Application versioning
# These would typically be updated by a CI/CD pipeline
current_version: "4.0.0"
previous_version: ""


node_exporter_version: "1.3.1"