$ANSIBLE_VAULT;1.1;AES256
32303165373337333430626566326461656361613862363663323330643436643234383863326636
6238373738366338396261623562643564313837353639630a356533316337396562303861373163
30373130366266636463623364303932366436656265663762383166623535636534613431393566
3933363039343663330a636538653530613139393036353838356435313331326263643131333838
61643835346236633366313839346139336461326461646434373231313433323139626138353964
35623537663865323034383065346132323538323566366635643130616339333563396162613430
31393635623234383632376338643132343634363362343136366364336634646431636231636335
30373232393830336134316361396462333866363039393135656264616661326236326233333435
30373630313931613337373162346136306534376266373031303362383630376136383163363661
62626434333865343139613366326564316430633738363033666461623537383465343461326337
36646338643730336437303239313237613365323335336131653466376364346130633539316137
33353838313265313235373066373232373438663332643131343732613831626330663635636231
6664
